version: '3.8'

services:
  frontend:
    build:
      context: ./animal-tracking 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  sqlite_data:
